import type {NextPage} from 'next'
import styles from '../styles/Home.module.css'
import Latest from "../components/pages/Latest/Latest";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            {/*<Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>*/}
            <Latest/>
        </div>
    )
}

export default Home
